version: "3.6"
services:
  beacon-validator:
    build:
      context: nimbus
      args:
        UPSTREAM_VERSION: v24.7.0
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      LOG_TYPE: INFO
      GRAFFITI: validating_from_DAppNode
      P2P_TCP_PORT: 9606
      P2P_UDP_PORT: 9606
      WEB3_BACKUP: ""
      CHECKPOINT_SYNC_URL: ""
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
    ports:
      - 9606:9606/tcp
      - 9606:9606/udp
    volumes:
      - nimbus-holesky-data:/home/user/nimbus-eth2/build/data
volumes:
  nimbus-holesky-data: {}
